apiVersion: v1
kind: Pod
metadata:
  name: nginx-tolerated
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - us-east-1d
            - us-east-1b
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: project
            operator: In
            values:
            - roboshoping
      - weight: 10
        preference:
          matchExpressions:
          - key: project
            operator: In
            values:
            - amazon  
  containers:
  - name: nginx
    image: nginx