apiVersion: v1
kind: Pod
metadata:
  name: nginx-tolerated
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - us-east-1d
  containers:
  - name: nginx
    image: nginx